#!/bin/bash
# COLOR VALIDATION

clear
y='\033[1;33m' #yellow
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[1;95m"
YELL='\033[0;33m'
rm /etc/xray/isp >> /dev/null 2>&1
rm /etc/xray/city >> /dev/null 2>&1
rm /etc/xray/timezone >> /dev/null 2>&1
curl -s ipinfo.io/org >> /etc/xray/isp
curl -s ipinfo.io/city >> /etc/xray/city
curl -s ipinfo.io/timezone >> /etc/xray/timezone
clear
