#!/bin/bash
######################################
BODAS="\033[97;1m"
NC="\033[0m"
######################################
MYIP=$(curl -sS ipv4.icanhazip.com)
IPVPS=$(curl -s ipv4.icanhazip.com)
echo ""
clear

######################################
# // INSTALL UDP CUSTOM
UDPX="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
######################################
green="\033[1;32m"
red="\033[1;31m"
clear
######################################
# // USERNAME IZIN IPP

######################################
# // DETAIL ORDER IZIN IP
username=$(cat /usr/bin/user)${NC}
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
######################################
# // VPS INFORMATION
DATE=$(date +'%Y-%m-%d')
datediff() {
    d1=$(date -d "$1" +%s)
    d2=$(date -d "$2" +%s)
    echo -e "$COLOR1 $NC Expiry In   : $(( (d1 - d2) / 86400 )) Days"
}
mai="datediff "$Exp" "$DATE""
######################################

clear
######################################
# // GETTINGS SYSTEM
uptime="$(uptime -p | cut -d " " -f 2-10)"
cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
cpu_usage+=" %"
WKT=$(curl -s ipinfo.io/timezone )
DAY=$(date +%A)
DATE=$(date +%m/%d/%Y)
DATE2=$(date -R | cut -d " " -f -5)
IPVPS=$(curl -s ipinfo.io/ip )
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
fram=$( free -m | awk 'NR==2 {print $4}' )
########
clear
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
########
clear
######################################
# // RUNNING SSH
######################################
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${green}ON${NC}"
else
   status_ssh="${red}OFF${NC} "
fi
######################################
# // RUNNING WEBSOCKET
######################################
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${green}ON${NC}"
else
    status_ws_epro="${red}OFF${NC} "
fi
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${green}ON${NC}"
else
   status_haproxy="${red}OFF${NC} "
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="${green}ON${NC}"
else
   status_xray="${red}OFF${NC} "
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="${green}ON${NC}"
else
   status_nginx="${red}OFF${NC} "
fi
######################################
# RUNNING DROPBEAR
######################################
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="${green}ON${NC}"
else
   status_dropbear="${red}OFF${NC} "
fi

######################################

# // UPDATE / REVISI all menu

######################################

# \\ Vless account //
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
# \\ Vmess account //
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
# \\ Trojan account //
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
# \\ shadowsocks account //
ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
let ssa=$ssx/2
BODAS="\033[97;1m"
NC="\033[0m"
######################################
# // GET INFO SYSTEM
USAGERAM=${BODAS}$(free -m | awk 'NR==2 {print $3}')${NC}
MEMOFREE=${BODAS}$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")${NC}
LOADCPU=${BODAS}$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")${NC}
DATEVPS=${BODAS}$(date +'%d/%m/%Y')${NC}
TIMEZONE=${BODAS}$(printf '%(%H:%M:%S)T')${NC}
SERONLINE=${BODAS}$(uptime -p | cut -d " " -f 2-10000)${NC}
######################################
# // OPERATING SYSTEM
MODEL=${BODAS}$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')${NC}
CORE=${BODAS}$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")${NC}
domain=${BODAS}$(cat /etc/xray/domain)${NC}
RAM=${BODAS}$(free -m | awk 'NR==2 {print $2}')${NC}
uram=${BODAS}$( free -m | awk 'NR==2 {print $3}' )${NC}
ISP=${BODAS}$(cat /etc/xray/isp)${NC}
CITY=${BODAS}$(cat /etc/xray/city)${NC}
cpu_usage="${BODAS}$((${cpu_usage1/\.*} / ${coREDiilik:-1}))${NC}"
# // ----->>> BACKGROUND
BG_RED="\033[41;1m" # BG MERAH
BG_GRN="\033[42;1m" # BG HIJAU
BG_YEL="\033[43;1m" # BG KUNING
BG_BLU="\033[44;1m" # BG BIRU
BG_PUR="\033[45;1m" # BG PINK
BG_CYN="\033[46;1m" # BG CYANN
BG_WHT="\033[47;1m" # BG PUTIH

# // ----->>> COLOR VALIDATIONS
GREEN="\033[92m"    # HIJAU
WHITE="\033[1;37m"  # PUTIH
CYAN="\033[96;1m"   # BIRUMUDA
BLUE="\033[1;34m"   # BIRU
RED='\033[0;31m'    # MERAH
NC='\033[0m'        # FINISHING
PINK="\033[95;1m"


SSHO="\033[97mSSH/UDP/OPVPN\033[0m"
VMSS="\033[97mVMESS x LIBEV\033[0m"
VLSS="\033[97mVLESS x LIBEV\033[0m"
TRJN="\033[97mTROJAN x XRAY\033[0m"
SDOW="\033[97mSHADOWSOCKS-R\033[0m"
###########
FTUR="\033[97mOTHER SETINGS\033[0m"
BCKP="\033[97mBACKUP/RESTOR\033[0m"
UPDT="\033[97mUPDATE SCRIPT\033[0m"
BOTT="\033[97mBOTT TELEGRAM\033[0m"
ONOF="\033[97mON OF LIMIT\033[0m"
EXIT="\033[91mEXIT         \033[0m"
###########
LINE1="\033[96;1m╔═════════════════════════════════════════════════════════╗\033[0m"
NGINX="\033[93;1mNGINX\033[0m"
EPROW="\033[93;1mWS-EPRO\033[0m"
PROXY="\033[93;1mHAPROXY\033[0m"
DROPB="\033[93;93mDROPBEAR\033[0m"
LINE2="\033[96;1m╚═════════════════════════════════════════════════════════╝\033[0m"
HORZ="\033[96;1m═════════════════\033[0m"
BGM1="\033[41;1m                 \033[0m"
BGG2="\033[46;1m                 \033[0m"
BGY3="\033[44;1m                 \033[0m"
BGP4="\033[45;1m                 \033[0m"



###########
VERTICAL="\033[96;1m║\033[0m"
###########
KOSONG=" "
# // system operating
SYS1="\033[92;1mOperating System: \033[0m"
SYS2="\033[92;1mIsp: \033[0m"
SYS3="\033[92;1mRegions: \033[0m"
SYS4="\033[92;1mCpu Usage: \033[0m"
SYS5="\033[92;1mRam: \033[0m"
SYS6="\033[92;1mIp vps: \033[0m"
SYS7="\033[92;1mDomain: \033[0m"
###########
ASSH="\033[95mSSH/OVPN\033[0m"
ATRJ="\033[95mTROJAN\033[0m"
AVLS="\033[95mVLESS\033[0m"
AVMS="\033[95mVMESS\033[0m"
ASDS="\033[95mSADOWSOCKS\033[0m"
###########
STATUS="\033[93mSTATUS    >>  \033[0m"
CLIENT="\033[93mCLIENT    >>  \033[0m"
EXPIRY="\033[93mEXPIRY    >>  \033[0m"
IP_VPS="\033[93mIP VPS    >>  \033[0m"
JIAHAHA1="\033[93m≛ 卍 ᴏᴛʜᴇʀ-ꜱ 卐 ≛      \033[0m"
JIAHAHA2="\033[93m≛ 卍 ᴀᴄᴄᴏᴜɴᴛ 卐 ≛\033[0m"
PERSEN="\033[97;1m%\033[0m"
###########
N1="\033[97;1m 1.\033[0m"
N2="\033[97;1m 2.\033[0m"
N3="\033[97;1m 3.\033[0m"
N4="\033[97;1m 4.\033[0m"
N5="\033[97;1m 5.\033[0m"
N6="\033[97;1m 6.\033[0m"
N7="\033[97;1m 7.\033[0m"
N8="\033[97;1m 8.\033[0m"
N9="\033[97;1m 9.\033[0m"
NX="\033[97;1m x.\033[0m"

clear
echo -e """
          $LINE1
              $NGINX : $status_nginx $DROPB : $status_dropbear $EPROW : $status_ws_epro $PROXY :  $status_haproxy       
          $LINE2
          $LINE1
          $VERTICAL  $SYS1$MODEL
          $VERTICAL  $SYS2$ISP
          $VERTICAL  $SYS3$CITY
          $VERTICAL  $SYS4$cpu_usage$PERSEN
          $VERTICAL  $SYS5$RAM 
          $VERTICAL  $SYS7$domain        
          $LINE2
          $LINE1
          $ASSH = $ssh1 $ATRJ = $trb  $AVLS = $vla $AVMS = $vma $ASDS = $ssa
          $LINE2
$KOSONG
                   $STATUS        ${sts}
                   $IP_VPS        $IPVPS
                   $CLIENT        $username
                   $EXPIRY        $exp / $certifacate Days
"""
echo -e  "          $LINE1"
echo -e  "          $VERTICAL $N1 $SSHO $VERTICAL$BGM1$VERTICAL $N6 $BCKP $VERTICAL"                        
echo -e  "          $VERTICAL $N2 $VMSS $VERTICAL$BGG2$VERTICAL $N7 $UPDT $VERTICAL"
echo -e  "          $VERTICAL $N3 $VLSS $VERTICAL$HORZ$VERTICAL $N8 $BOTT $VERTICAL"
echo -e  "          $VERTICAL $N4 $TRJN $VERTICAL$BGY3$VERTICAL $N9 $FTUR $VERTICAL"
echo -e  "          $VERTICAL $N5 $SDOW $VERTICAL$BGP4$VERTICAL $NX $EXIT $VERTICAL"
echo -e  "          $LINE2"
echo -e " "
read -p " Select Options [ 1 / 10 or x ] :    " manu
case $wZtXtQXTZoo menu
1)
clear
m-sshws
;;
2)
clear
m-vmess
;;
3)
clear
m-vless
;;
4)
clear
m-trojan
;;
5)
clear
m-ssws
;;
6)
clear
m-backup
;;
7)
clear
update
;;
8)
clear
m-bott
;;
9)
clear
m-others
;;
*)
clear
exit
;;
esac
